name: citra-mts
version: git
confinement: strict
base: core18
grade: stable
#icon: https://github.com/citra-emu/citra/raw/master/dist/icon.png
architectures:
  - build-on: [amd64]
    run-on: [amd64]

summary: Nintendo 3DS Emulator
description: |
  Citra is a work-in-progress Nintendo 3DS emulator started in early 2014.
  Citra can currently emulate, with varying degrees of success, a wide variety of different homebrew applications and commercial software.

parts:

  prepare:
    plugin: nil
    build-snaps: [ffmpeg]
    stage-snaps: [ffmpeg]
    build-packages: [pkg-config, dpkg-dev, build-essential, libsdl2-dev, qtbase5-dev, libqt5opengl5-dev, qtmultimedia5-dev]
    stage-packages: [libsdl2-dev, qtbase5-dev, libqt5opengl5-dev, qtmultimedia5-dev]
    after: [desktop-qt5]

  wrapper:
    plugin: nil
    organize:
      'citra-canary': bin/canary
      'citra-nightly': bin/nightly
    after: [citra-nightly]
  
  citra-canary:
    plugin: cmake
    source: https://github.com/citra-emu/citra-canary.git
    source-tag: canary-1343
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/bin/canary]
    after: [prepare]
  
  citra-nightly:
    plugin: cmake
    source: https://github.com/citra-emu/citra-nightly.git
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/bin/nightly]
    after: [citra-canary]
    
  desktop-qt5:
    build-packages: [build-essential, qtbase5-dev, dpkg-dev]
    make-parameters: [FLAVOR=qt5 -j $SNAPCRAFT_PARALLEL_BUILD_COUNT]
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages: [libxkbcommon0, ttf-ubuntu-font-family, dmz-cursor-theme, light-themes, adwaita-icon-theme, gnome-themes-standard, shared-mime-info, libqt5gui5, libgdk-pixbuf2.0-0, libqt5svg5, try: [appmenu-qt5, locales-all, xdg-user-dirs, fcitx-frontend-qt5]]

apps:

  citra-canary:
    command: desktop-launch bin/canary/bin/citra-qt
    plugs: [home, network, pulseaudio, alsa, x11, wayland, desktop, desktop-legacy, opengl, screen-inhibit-control]
    #desktop: bin/canary/share/applications/citra.desktop

  citra-nightly:
    command: desktop-launch bin/nightly/bin/citra-qt
    plugs: [home, network, pulseaudio, alsa, x11, wayland, desktop, desktop-legacy, opengl, screen-inhibit-control]
    #desktop: bin/canary/share/applications/citra.desktop
