name: citra-mts
version: git
confinement: strict
base: core18
grade: stable
#icon: https://github.com/citra-emu/citra/raw/master/dist/icon.png
architectures:
  - build-on: [amd64]
    run-on: [amd64]

summary: Nintendo 3DS Emulator
description: |
  Citra is a work-in-progress Nintendo 3DS emulator started in early 2014.
  Citra can currently emulate, with varying degrees of success, a wide variety of different homebrew applications and commercial software.

parts:

  prepare:
    plugin: nil
    build-snaps: [ffmpeg]
    stage-snaps: [ffmpeg]
    build-packages: [pkg-config, dpkg-dev, build-essential, libsdl2-dev, qtbase5-dev, libqt5opengl5-dev, qtmultimedia5-dev]
    stage-packages: [libsdl2-dev, qtbase5-dev, libqt5opengl5-dev, qtmultimedia5-dev]

  wrapper:
    plugin: nil
    organize:
      'citra-canary': canary
      'citra-nightly': nightly
    after: [citra-nightly]
  
  citra-canary:
    plugin: cmake
    source: https://github.com/citra-emu/citra-canary.git
    source-tag: canary-1343
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/canary]
    after: [prepare]
  
  citra-nightly:
    plugin: cmake
    source: https://github.com/citra-emu/citra-nightly.git
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/nightly]
    after: [citra-canary]
    
apps:

  citra-canary:
    command: sh $SNAP/canary/bin/citra-qt
    plugs: [home, network, pulseaudio, alsa, x11, desktop, desktop-legacy, opengl, screen-inhibit-control]
    #desktop: canary/share/applications/citra.desktop

  citra-nightly:
    command: sh $SNAP/nightly/bin/citra-qt
    plugs: [home, network, pulseaudio, alsa, x11, desktop, desktop-legacy, opengl, screen-inhibit-control]
    #desktop: nightly/share/applications/citra.desktop
